### PR TITLE
Low nonce consumption

### LINKED ISSUE #228: Wrong "state" migrating from 3.1.0 to 3.2.0
Migrating from version 3.1.0 to 3.2.0 no signatures occur with this error

`Cosigner failed to set nonces and sign       chain_id=xxx-1 height=xxx round=0 type=prevote cosigner=1 err="unexpected state, metadata does not exist for U: xxxxx"`

The steps performed:

- stop all sentry/nodes
- stop all signers
- update bin
- rm -rf /raft
- start all signers
- start sentry/nodes

The same in test with a stand-alone setup (--accept-risk) with a wrong state file.
In this last case I solved it increasing blocks without signatures and then by deleting `state/priv_validator_state.json` (it's a testnet)

Some idea?
Thanks

### PR DESCRIPTION
**Pull request by agouin**
Fine tune when nonces are being consumed at a delay greater than the getNoncesInterval

When nonces are being consumed at a rate less than the getNoncesInterval, the resulting signal makes it difficult to estimate the correct target that will prevent expiring nonces and also prevent cached nonces dropping to zero.

This introduces a better moving average mechanism to more accurately determine the rate of nonce consumption, and enables reconciling to get more nonces as soon as the cache is empty.

Resolves #228

### CODE REVIEW

File: signer/cosigner_nonce_cache.go [hunk 1]
```diff
@@ -36,6 +34,56 @@ type CosignerNonceCache struct {
...
+		m.items[:keep+1]...,
+	)
+}
+
+func (m *movingAverage) average() float64 {
+	weightedSum := float64(0)
+	duration := float64(0)
+
+	for _, e := range m.items {
+		d := float64(e.timeSinceLastReconcile)
```
Comment (misko9) [inline signer/cosigner_nonce_cache.go:81]: Won't this result in returning nonces/nanosecond? Maybe this: `d := e.timeSinceLastReconcile.Minutes()`?

Comment (misko9) [reply signer/cosigner_nonce_cache.go:81]: Actually, the scaling doesn't matter since it cancels itself out.

**Review by misko9 — APPROVED** [review]
